name: mat
channels:
  - defaults
dependencies:
  - jupyter
  - numpy
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - ipympl
  - seaborn
  - voila

  Installed with pip:
  - Flask==2.2.3 
  - "connexion[swagger-ui]==2.14.1"
