# swagger.yml

openapi: 3.0.0
info:
  title: "Time Series Insight Toolkit Flask REST API"
  description: "An API for records"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  #schemas:
  #  Group:
  #    type: "object"
  #    required:
  #      - name
  #    properties:
  #      name:
  #        type: "string"
  parameters:
    group:
      name: "group"
      description: "Name of the group to get"
      in: path
      required: True
      schema:
        type: "string"
    version:
      name: "version"
      description: "String identifieng the preprocessed data version"
      in: path
      required: True
      schema:
        type: "string"
    record:
      name: "record"
      description: "String identifieng the record"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /raw:
    get:
      operationId: "registry.read_raw"
      tags:
        - "Raw groups"
      summary: "Read the list of raw records groups"
      responses:
        "200":
          description: "Successfully read raw groups"

  /raw/{group}:
    get:
      operationId: "registry.read_raw_groups"
      tags:
        - Raw groups
      summary: "Read the recods in a raw group"
      parameters:
        - $ref: "#/components/parameters/group"
      responses:
        "200":
          description: "Successfully read  raw group"

  /proc:
    get:
      operationId: "registry.read_proc"
      tags:
        - "Processed groups"
      summary: "Read the list of processed records groups"
      responses:
        "200":
          description: "Successfully read processed groups"

  /proc/{group}:
    get:
      operationId: "registry.read_all_proc_group_versions"
      tags:
        - Processed groups
      summary: "Read the processed data versions in a processed group"
      parameters:
        - $ref: "#/components/parameters/group"
      responses:
        "200":
          description: "Successfully read processed group versions"

  /proc/{group}/{version}/:
    get:
      operationId: "registry.read_proc_group_version"
      tags:
        - Processed groups
      summary: "Read the recods in a proccessed verion group"
      parameters:
        - $ref: "#/components/parameters/group"
        - $ref: "#/components/parameters/version"
      responses:
        "200":
          description: "Successfully read processed group version"

  /proc/{group}/{version}/{record}:
    get:
      operationId: "registry.read_proc_group_version_record"
      tags:
        - Processed groups
      summary: "Read the recod json in a proccessed verion group"
      parameters:
        - $ref: "#/components/parameters/group"
        - $ref: "#/components/parameters/version"
        - $ref: "#/components/parameters/record"
      responses:
        "200":
          description: "Successfully read processed group record"
  
  /proc/{group}/{version}/{record}/plot:
    get:
      operationId: "registry.plot_record"
      tags:
        - Processed groups
      summary: "Plot the recod json in a proccessed verion group"
      parameters:
        - $ref: "#/components/parameters/group"
        - $ref: "#/components/parameters/version"
        - $ref: "#/components/parameters/record"
      responses:
        "200":
          description: "Successfully plotted processed group record"
          content:
            image/png:
              schema:
                type: string
                format: binary


  #/proc/<group>/pars:
  #  get:
  #    operationId: "registry.read_proc_pars"
  #    tags:
  #      - "Processed groups"
  #    summary: "Read the parameters used for the processed records groups"
  #    responses:
  #      "200":
  #        description: "Successfully processed group parameter"