# swagger.yml

openapi: 3.0.0
info:
  title: "Time Series Insight Toolkit Flask REST API"
  description: "An API for records fram capture events"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  #schemas:
  #  Group:
  #    type: "object"
  #    required:
  #      - name
  #    properties:
  #      name:
  #        type: "string"
  parameters:
    eid:
      name: "eid"
      description: "Capture event ID of the session"
      in: path
      required: True
      schema:
        type: "string"
    gid:
      name: "gid"
      description: "Group ID of the session"
      in: path
      required: True
      schema:
        type: "string"
    version:
      name: "version"
      description: "Version ID of the sesseion"
      in: path
      required: True
      schema:
        type: "string"
    record:
      name: "record"
      description: "String identifieng the record"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /raw:
    get:
      operationId: "registry.read_raw"
      tags:
        - "Raw groups"
      summary: "Read the list of capture events with raw records groups"
      responses:
        "200":
          description: "Successfully read events with raw groups"

  /raw/{eid}/:
    get:
      operationId: "registry.read_raw_event"
      tags:
        - "Raw groups"
      summary: "Read the list of raw records groups in the capute event"
      parameters:
        - $ref: "#/components/parameters/eid"
      responses:
        "200":
          description: "Successfully read raw groups"

  /raw/{eid}/session/{gid}:
    get:
      operationId: "registry.read_raw_groups"
      tags:
        - Raw groups
      summary: "Read the recods in a raw group"
      parameters:
        - $ref: "#/components/parameters/eid"
        - $ref: "#/components/parameters/gid"
      responses:
        "200":
          description: "Successfully read  raw group"

  /proc:
    get:
      operationId: "registry.read_proc"
      tags:
        - "Processed groups"
      summary: "Read the list of capture events with processed records groups"
      responses:
        "200":
          description: "Successfully read events with processed groups"

  /proc/{eid}/:
    get:
      operationId: "registry.read_proc_event"
      tags:
        - "Processed groups"
      summary: "Read the list of processed records groups in the capture event"
      parameters:
        - $ref: "#/components/parameters/eid"
      responses:
        "200":
          description: "Successfully read events with processed groups"

  /proc/{gid}:
    get:
      operationId: "registry.read_all_proc_group_versions"
      tags:
        - Processed groups
      summary: "Read the processed data versions in a processed group"
      parameters:
        - $ref: "#/components/parameters/gid"
      responses:
        "200":
          description: "Successfully read processed group versions"

  /proc/{gid}/{version}/:
    get:
      operationId: "registry.read_proc_group_version"
      tags:
        - Processed groups
      summary: "Read the recods in a proccessed verion group"
      parameters:
        - $ref: "#/components/parameters/gid"
        - $ref: "#/components/parameters/version"
      responses:
        "200":
          description: "Successfully read processed group version"

  /proc/{gid}/{version}/{record}:
    get:
      operationId: "registry.read_proc_group_version_record"
      tags:
        - Processed groups
      summary: "Read the recod json in a proccessed verion group"
      parameters:
        - $ref: "#/components/parameters/gid"
        - $ref: "#/components/parameters/version"
        - $ref: "#/components/parameters/record"
      responses:
        "200":
          description: "Successfully read processed group record"
  
  /proc/{gid}/{version}/{record}/plot:
    get:
      operationId: "registry.plot_record"
      tags:
        - Processed groups
      summary: "Plot the recod json in a proccessed verion group"
      parameters:
        - $ref: "#/components/parameters/gid"
        - $ref: "#/components/parameters/version"
        - $ref: "#/components/parameters/record"
      responses:
        "200":
          description: "Successfully plotted processed group record"
          content:
            image/png:
              schema:
                type: string
                format: binary


  #/proc/<group>/pars:
  #  get:
  #    operationId: "registry.read_proc_pars"
  #    tags:
  #      - "Processed groups"
  #    summary: "Read the parameters used for the processed records groups"
  #    responses:
  #      "200":
  #        description: "Successfully processed group parameter"