# swagger.yml

openapi: 3.0.0
info:
  title: "Time Series Insight Toolkit Flask REST API"
  description: "An API for records"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  #schemas:
  #  Group:
  #    type: "object"
  #    required:
  #      - name
  #    properties:
  #      name:
  #        type: "string"
  parameters:
    group:
      name: "group"
      description: "Name of the group to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /raw:
    get:
      operationId: "registry.read_raw"
      tags:
        - "Raw groups"
      summary: "Read the list of raw records groups"
      responses:
        "200":
          description: "Successfully read raw groups"
  /proc:
    get:
      operationId: "registry.read_proc"
      tags:
        - "Processed groups"
      summary: "Read the list of processed records groups"
      responses:
        "200":
          description: "Successfully read processed groups"

  /raw/{group}:
    get:
      operationId: "registry.read_group"
      tags:
        - Groups
      summary: "Read the recods in a raw group"
      parameters:
        - $ref: "#/components/parameters/gName"
      responses:
        "200":
          description: "Successfully read  raw group"

  #/proc/<group>/pars:
  #  get:
  #    operationId: "registry.read_proc_pars"
  #    tags:
  #      - "Processed groups"
  #    summary: "Read the parameters used for the processed records groups"
  #    responses:
  #      "200":
  #        description: "Successfully processed group parameter"